spring:
  application:
    name: ai-code-mother-backend
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_ai_coding?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 10280017
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.example.aicodemother.controller
